services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
        container_name: elasticsearch
        environment:
            - cluster.name=elasticsearch
            - xpack.security.enabled=false
            - discovery.type=single-node
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
volumes:
    elasticsearch-data:
        driver: local
