spring:
    application:
        name: demo
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: localhost:9200
    elasticsearch:
        uris: localhost:9200

server:
    port: 9001
